### ISSUE TITLE
看大佬学习git

### ISSUE THREAD

**Issue by ZhangGaoxing** [nnnnnnnnnni/gittest#5]

**Comment by nnnnnnnnnni** [comment]
OK。批准了

**Comment by ZhangGaoxing** [comment]
在加班啊🤣

________________________________
发件人: nnnnnnnnnni <notifications@github.com>
发送时间: Wednesday, October 16, 2019 7:38:16 PM
收件人: nnnnnnnnnni/gittest <gittest@noreply.github.com>
抄送: Zhang Yuexin <zhangyuexin121@live.cn>; Author <author@noreply.github.com>
主题: Re: [nnnnnnnnnni/gittest] 看大佬学习git (#5)


OK。批准了
